import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "text-tertiary": "#6B5F72",
        "surface-dim": "#1a1015",
        "primary-fixed": "#e0e0ff",
        surface: "#241820",
        "on-tertiary": "#3b2f00",
        background: "#1a1015",
        "on-background": "#f1dde5",
        "primary-fixed-dim": "#bfc2ff",
        "on-primary-container": "#222665",
        "border-subtle": "rgba(139, 143, 212, 0.15)",
        error: "#ffb4ab",
        elevated: "#2E1F28",
        "on-primary-fixed-variant": "#3c4080",
        "text-primary": "#FFFFFF",
        "surface-bright": "#42363b",
        "inverse-primary": "#545899",
        "secondary-fixed-dim": "#bbc3ff",
        "outline-variant": "#464650",
        "on-secondary": "#001c95",
        "text-secondary": "#A89DB0",
        "on-primary": "#252968",
        "inverse-surface": "#f1dde5",
        "border-accent": "rgba(139, 143, 212, 0.35)",
        tertiary: "#e1c562",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#564500",
        "on-error": "#690005",
        "surface-variant": "#3e3137",
        "tertiary-container": "#c4a94a",
        "tertiary-fixed": "#ffe17b",
        "on-tertiary-container": "#4d3e00",
        "secondary-container": "#2138b9",
        "secondary-fixed": "#dee0ff",
        "on-surface-variant": "#c7c5d1",
        "surface-container-low": "#23191e",
        "surface-tint": "#bfc2ff",
        "surface-container-highest": "#3e3137",
        "surface-container-high": "#32272c",
        "gradient-end": "#F0A830",
        "on-primary-fixed": "#0e1152",
        "surface-container": "#271c22",
        "on-error-container": "#ffdad6",
        outline: "#918f9b",
        "gradient-start": "#6B7FFF",
        "tertiary-fixed-dim": "#e1c562",
        "gradient-warm": "#E8825A",
        "gradient-mid": "#9B6FD4",
        "on-surface": "#f1dde5",
        "on-tertiary-fixed": "#231b00",
        "surface-container-lowest": "#150b10",
        primary: "#bfc2ff",
        secondary: "#bbc3ff",
        "inverse-on-surface": "#392d33",
        "on-secondary-fixed": "#000e5e",
        "primary-container": "#8b8fd4",
        "on-secondary-container": "#a9b3ff",
        "on-secondary-fixed-variant": "#1e35b7",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "stack-md": "12px",
        "stack-sm": "8px",
        "stack-lg": "16px",
        "container-max": "1440px",
        "navbar-height": "52px",
        "sidebar-width": "200px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
